version: '2'

services:

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - ./logs:/var/logs/postgresql
    ports:
      - 5433:5432
    env_file:
      - .env
    networks:
      coach-network:
        ipv4_address: 192.168.10.10

networks:
  coach-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1