version: '3'

services:

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - ./logs:/var/logs/postgresql
    ports:
      - 5432:5432
    env_file:
      - .env
